### ISSUE TITLE
Daily builds of skopeoimage produce new images each time (when no changes in base image or skopeo binary)

### ISSUE THREAD

**Issue by mtrmac** [containers/automation_images#310] opened 2023-10-23 18:57 UTC
Originally reported in https://github.com/containers/skopeo/issues/2133 :

---

Currently, image builds are not idempotent (for example `quay.io/skopeo/stable:latest` image):

```sh
# using container-diff from https://github.com/GoogleContainerTools/container-diff

sudo container-diff diff daemon://quay.io/skopeo/stable@sha256:$PREV_HASH daemon://quay.io/skopeo/stable@sha256:$CUR_HASH --type=file

-----File-----

These entries have been added to quay.io/skopeo/stable@sha256:$PREV_HASH: None

These entries have been deleted from quay.io/skopeo/stable@sha256:$PREV_HASH: None

These entries have been changed between quay.io/skopeo/stable@sha256:$PREV_HASH and quay.io/skopeo/stable@sha256:$CUR_HASH:
FILE                                                               SIZE1        SIZE2
/usr/lib/sysimage/rpm/rpmdb.sqlite                                 8.6M         8.6M
/var/lib/dnf/history.sqlite-wal                                    3.9M         3.9M
/etc/pki/ca-trust/extracted/java/cacerts                           158K         158K
/var/lib/dnf/history.sqlite                                        132K         132K
/var/lib/dnf/history.sqlite-shm                                    32K          32K
/etc/shadow                                                        504B         504B
/etc/shadow-                                                       475B         475B
/var/log/hawkey.log                                                240B         240B
/etc/machine-id                                                    33B          33B
/var/lib/dnf/repos/fedora-376ef8e983c65ce0/countme                 26B          12B
/var/lib/dnf/repos/updates-modular-29738c1a65877bb4/countme        26B          12B
/var/lib/dnf/repos/updates-b7ba662710b98f1a/countme                12B          12B
```

**Comment by cevich** [comment] 2024-02-08 18:58
Update: I'm currently working on a chain of tasks that will result in us publishing some unchanging image tags.  Most likely they will be tags with a suffix of `-stable` or something similar.

Actually, I think the tracker for this is public:
https://issues.redhat.com/browse/RUN-2025

**Comment by ethankent** [comment] 2024-02-08 21:27
Hi @cevich I had one further thought that I'd like to share here. In my particular use-case, I'd like to be able to pin to a digest and allow for automated tools ([Dependabot](https://docs.github.com/en/code-security/dependabot), et. al.) to find new versions. For example if I were to specify:

```
FROM quay.io/skopeo/stable:v1.14.0@sha256:3eeae9f95a5f5ebc9ceca4b1745040ffb22db4b4bf6027bb933925e571701b7e AS skopeo
```

Dependabot would know it should make an update when the tag increments and/or the digest changes. With any luck, this will work in your updated pipeline without any effort. I just wanted to make sure you're at least aware of this desired functionality, so that you can decide if it's something you'd like to specifically test for.

Also as I typed this out, I occurred to me that you might find it awkward to name the image `skopeo/stable-stable`. Perhaps the current functionality should be retained under a new name like `skopeo/nightly`, or pushed as a "pre-release"?

I hope my feedback is helpful. I'm looking forward to seeing what you come up with.

**Comment by cevich** [comment] 2024-02-08 22:07
Thanks for the feedback.  Yes, I'm sensitive to the dependabot and Renovate use-cases.  I dunno about dependabot, but Renovate uses the OCI image labels to figure out versions.  IIRC, it uses 'loose' semantic versioning by default, which would be compatible to their having a suffix after the version.

Hmmm, you're right about the weird looking name.  Maybe '-static' would be better? Continuing the skopeo example and picking a random version, the images would be as follows, and initially all point at the same thing.  Though that would change with every periodic build, except the `-static` tags that would be untouched:

quay.io/skopeo/stable:latest
quay.io/skopeo/stable:1.13.3
quay.io/skopeo/stable:1.13.3-static
quay.io/skopeo/stable:1.13
quay.io/skopeo/stable:1.13-static
quay.io/skopeo/stable:1
quay.io/skopeo/stable:1-static

quay.io/containers/skopeo:latest
quay.io/containers/skopeo:1.13.3
quay.io/containers/skopeo:1.13.3-static
quay.io/containers/skopeo:1.13
quay.io/containers/skopeo:1.13-static
quay.io/containers/skopeo:1
quay.io/containers/skopeo:1-static

**Comment by ethankent** [comment] 2024-02-16 17:38
Thanks again @cevich. I’m definitely looking forward to trying that out.

**Comment by ethankent** [comment] 2024-02-19 21:30
Hello again @cevich  - I wanted to share a thought that might make things easier and/or more semantic.

Many images will include a keyword indicating the base image that's being used. `node:20.11.1-alpine` is one example. So If it's feasible to create a build based on `scratch` - copying the binary + required libs, that would provide a conventionally semantic image name `quay.io/containers/skopeo:1.13.3-scratch`. And, it would likely accomplish an acceptable fix for this issue. Assuming of course, that the unwieldy amount of spurious changes are caused by underlying OS & library changes.

Hopefully this is helpful. Thanks again for looking into this issue.

**Comment by cevich** [comment] 2024-02-20 16:33
Thank you for the feedback.  So if I understand correctly, these images being Fedora based, you propose I use a `-fedora` suffix instead of `-static`?

Assuming so, I agree that `-static` could be confusing in that these images are **not** actually providing staticly-compiled binaries.  So scratch copying wouldn't be possible w/o knowing which shared libraries to also haul over.

Some other possible suffix options could be:
* `-eternal`
* `-immutable`
* `-unvarying`
* `-perpetual`

**Comment by ethankent** [comment] 2024-02-27 19:52
Hello again @cevich,

I'm actually recommending using the `-scratch` suffix, and hauling over the shared libraries. I'm currently accomplishing this with the [ldd](https://linux.die.net/man/1/ldd) utility.

```dockerfile
COPY --from=skopeo /bin/skopeo /bin/skopeo
# generated via
# ldd /bin/skopeo
# see also: https://linux.die.net/man/1/ldd
COPY --from=skopeo /lib/ld-linux-aarch64.so.1 /lib/ld-linux-aarch64.so.1
COPY --from=skopeo /lib64/libresolv.so.2 /lib64/libresolv.so.2
COPY --from=skopeo /lib64/libgpgme.so.11 /lib64/libgpgme.so.11
COPY --from=skopeo /lib64/libdevmapper.so.1.02 /lib64/libdevmapper.so.1.02
COPY --from=skopeo /lib64/libc.so.6 /lib64/libc.so.6
COPY --from=skopeo /lib64/libassuan.so.0 /lib64/libassuan.so.0
COPY --from=skopeo /lib64/libgpg-error.so.0 /lib64/libgpg-error.so.0
COPY --from=skopeo /lib64/libselinux.so.1 /lib64/libselinux.so.1
COPY --from=skopeo /lib64/libudev.so.1 /lib64/libudev.so.1
COPY --from=skopeo /lib64/libm.so.6 /lib64/libm.so.6
COPY --from=skopeo /lib64/libpcre2-8.so.0 /lib64/libpcre2-8.so.0
COPY --from=skopeo /lib64/libcap.so.2 /lib64/libcap.so.2
COPY --from=skopeo /lib64/libgcc_s.so.1 /lib64/libgcc_s.so.1
COPY --from=skopeo /etc/containers/policy.json /etc/containers/policy.json
```

All of the other options you've proposed seem like they'll get the job done also. I just figured I'd volunteer this in case it provides you with more choices.

**Comment by cevich** [comment] 2024-02-27 20:35
I'll need to talk this over with the team, but my gut is they'll say no.  It may be okay for the skopeo image.  But for podman and buildah I think they want some minimal extra tooling available (like `dnf`) - which hauls in an entire python stack :disappointed:

**Comment by ethankent** [comment] 2024-02-29 17:11
Fair enough. This looked like a simple & semantic solution to me. But if it doesn't look feasible for any reason, I'm sure the original solution using a `-static` (or other) suffix would be completely sufficient.

**Comment by cevich** [comment] 2024-03-04 20:07
So in the case of Skopeo this seems more possible.  For the buildah and podman images though it's not going to work.  There's too many necessary dependencies in those images for an ldd hack to work long-term.  i.e. crun, pasta, shadow-utils, dnf, etc.  Though I do like the idea in terms of drastically shrinking the image size, unfortunately we've gotten enough community push-back that even replacing dnf -> microdnf isn't very possible :confounded:

**Closed** 2024-04-19 17:41 UTC
